Fix grammatical issues and typos in the README
gramework/gramework pull request #41
Opened 2018-10-01 20:19 UTC by romshark

Fix numerous grammatical issues and typos in the README.
Add missing links.
reformulate some of the sentences in the README to proper English.

2018-10-01 20:19 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/gramework/gramework?pullRequest=41) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/gramework/gramework?pullRequest=41) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/gramework/gramework?pullRequest=41) it.</sub>

2018-10-01 20:31 UTC, kirillDanshin requested changes

2018-10-01 20:31 UTC, kirillDanshin commented on docs/README.md
> +- Gramework is made by the [maintainer](https://github.com/valyala) of [fasthttp](https://github.com/valyala/fasthttp).
`[maintainer](https://github.com/kirillDanshin)`

2018-10-01 20:31 UTC, kirillDanshin commented
Thanks!

2018-10-02 06:45 UTC, toby3d approved these changes
Everything seems fine

2018-10-02 16:00 UTC, kirillDanshin approved these changes

2018-10-02 16:00 UTC, merged